var gaji = 4500000;
var pajak = 0.025;
var bpjs = 250000;
var infak = 50000;
var transport = 10000;
var hari = 24;
var hasilpajak = gaji * pajak;
var totalpotong = hasilpajak + bpjs + infak;
var totaltunjangan = transport * hari;
var gajibersih = gaji - totalpotong + totaltunjangan;

console.log("Gaji Kotor : "+gaji);
console.log("===============================");
console.log("Potongan Pajak 2,5% : Rp."+hasilpajak);
console.log("Potongan BPJS : Rp."+bpjs);
console.log("Potongan Infak : Rp."+infak);
console.log("===============================");
console.log("Total Potongan : Rp."+totalpotong);
console.log("===============================");
console.log("Tunjangan Transport : Rp."+transport);
console.log("Total Hari Kerja : "+hari);
console.log("===============================");
console.log("Total Tunjangan : Rp."+totaltunjangan);
console.log("===============================");
console.log("Perhitungan Gaji : ");
console.log("(Gaji Kotor - Potongan) + Tunjangan");
console.log("(" + gaji+ "-" +totalpotong+ ") + " +totaltunjangan );
console.log("===============================");
console.log("Gaji Bersih : Rp."+gajibersih);